# Generated by Django 4.1 on 2023-09-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Efecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("parametros", models.JSONField()),
                (
                    "archivo_sample",
                    models.FileField(blank=True, null=True, upload_to="efectos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstacionRadio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("url_streaming", models.URLField()),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("archivo_sample", models.FileField(upload_to="samples/")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("percusion", "Percusión"),
                            ("cuerda", "Cuerda"),
                            ("viento", "Viento"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Melodía",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("archivo_midi", models.FileField(upload_to="melodias/")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "instrumentos_utilizados",
                    models.ManyToManyField(to="generator.instrumento"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("archivo_audio", models.FileField(upload_to="ambientales/")),
            ],
        ),
        migrations.CreateModel(
            name="Secuencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.TextField()),
                ("duracion", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=100, unique=True)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contraseña", models.CharField(max_length=100)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VersionMelodia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_version", models.DateTimeField(auto_now_add=True)),
                ("archivo_midi", models.FileField(upload_to="versiones/")),
                ("descripcion", models.TextField()),
                (
                    "melodia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.melodía",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recomendacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("referencia", models.IntegerField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferenciasUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genero_preferido", models.CharField(max_length=50)),
                ("configuracion_lofi", models.JSONField()),
                (
                    "instrumentos_favoritos",
                    models.ManyToManyField(to="generator.instrumento"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="melodía",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="generator.usuario"
            ),
        ),
        migrations.CreateModel(
            name="GeneracionLofi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuracion", models.JSONField()),
                ("archivo_generado", models.FileField(upload_to="generated/")),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "melodia_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.melodía",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("fecha_comentario", models.DateTimeField(auto_now_add=True)),
                (
                    "melodia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.melodía",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Colaboracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=50)),
                (
                    "melodia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.melodía",
                    ),
                ),
                (
                    "usuario_colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboraciones_recibidas",
                        to="generator.usuario",
                    ),
                ),
                (
                    "usuario_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboraciones_iniciadas",
                        to="generator.usuario",
                    ),
                ),
            ],
        ),
    ]
