# Generated by Django 4.1 on 2023-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "generator",
            "0002_autoencodermodel_chord_composition_experimenthistory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="audio_file",
            field=models.FileField(default=1, upload_to="note_audio/"),
            preserve_default=False,
        ),
    ]
