# Generated by Django 4.1 on 2023-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_note_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='audio_file',
            field=models.FileField(upload_to='notes_audio/'),
        ),
    ]
