# Generated by Django 4.1 on 2023-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_song_video_file_song_video_link_alter_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pattern', models.BinaryField()),
            ],
        ),
    ]
